{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pulseboard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pulseboard.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          # API — all /api/* and /health + /metrics traffic
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "pulseboard.api.fullname" . }}
                port:
                  name: http
          - path: /health
            pathType: Exact
            backend:
              service:
                name: {{ include "pulseboard.api.fullname" . }}
                port:
                  name: http
          - path: /metrics
            pathType: Exact
            backend:
              service:
                name: {{ include "pulseboard.api.fullname" . }}
                port:
                  name: http
          # Frontend — everything else
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "pulseboard.frontend.fullname" . }}
                port:
                  name: http
{{- end }}
